remote_theme: just-the-docs/just-the-docs
title: Lora Johnson

nav_external_links:
  - title: "Mortgage Delinquency Rates"
    url: "https://lora-johnson.github.io/mortgage-business-analysis/#mortgage-delinquency-rates"
  - title: "Loan-to-Value and Debt-to-Income Ratios"
    url: "https://lora-johnson.github.io/mortgage-business-analysis/#loan-to-value-and-debt-to-income-ratios"
  - - title: "What are “Bad” LTV and DTI Ratios?"
      url: "https://lora-johnson.github.io/mortgage-business-analysis/#what-are-bad-ltv-and-dti-ratios"
  

